"use client";
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Teacher.glb -r public -o src/components/Teacher.jsx
*/

import { lawyers, useAILawyer } from "@/hooks/useAILawyer";
import { Html, useAnimations, useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import { useEffect, useRef, useState } from "react";
import { MathUtils, MeshStandardMaterial } from "three";
import { randInt } from "three/src/math/MathUtils";

const ANIMATION_FADE_TIME = 0.5;

const CHARACTER_FILE = "/models/doozy/main.glb";
const ANIMATIONS_FILE = "/models/doozy/animations_v2.glb";

export function Avatar({ Avatar, animation, ...props }) {
  const group = useRef();
  const { scene } = useGLTF(CHARACTER_FILE);
  useEffect(() => {
    scene.traverse((child) => {
      if (child.material) {
        child.material = new MeshStandardMaterial({
          map: child.material.map,
        });
      }
    });
  }, [scene]);

  const currentMessage = useAILawyer((state) => state.currentMessage);
  const loading = useAILawyer((state) => state.loading);
  const { animations } = useGLTF(ANIMATIONS_FILE);
  const { actions, mixer } = useAnimations(animations, group);
  const [currentAnimation, setCurrentAnimation] = useState("bored");

  // Blinking effect
  const [blink, setBlink] = useState(false);
  useEffect(() => {
    let blinkTimeout;
    const nextBlink = () => {
      blinkTimeout = setTimeout(() => {
        setBlink(true);
        setTimeout(() => {
          setBlink(false);
          nextBlink();
        }, 100);
      }, randInt(1000, 5000));
    };
    nextBlink();
    return () => clearTimeout(blinkTimeout);
  }, []);

  // Animation control
  useEffect(() => {
    let interval = null;

    if (loading) {
      setCurrentAnimation("bored");
    } else if (currentMessage) {
      setCurrentAnimation("talking");
    } else {
      setCurrentAnimation(animation || "bored");
    }

    return () => {
      if (interval) clearInterval(interval);
    };
  }, [currentMessage, loading, animation]);

  useFrame(({ camera }) => {
    // Smile
    lerpMorphTarget("mouthSmile", 0.2, 0.5);
    // Blinking
    lerpMorphTarget("eye_close", blink ? 1 : 0, 0.5);

    // Talking
    for (let i = 0; i <= 21; i++) {
      lerpMorphTarget(i, 0, 0.1); // reset morph targets
    }

    if (
      currentMessage &&
      currentMessage.visemes &&
      currentMessage.audioPlayer
    ) {
      for (let i = currentMessage.visemes.length - 1; i >= 0; i--) {
        const viseme = currentMessage.visemes[i];
        if (currentMessage.audioPlayer.currentTime * 1000 >= viseme[0]) {
          lerpMorphTarget(viseme[1], 1, 0.2);
          break;
        }
      }
    }
  });

  useEffect(() => {
    // Validate animation exists
    const validAnimations = [
      "bored",
      "hip_hop_dancing",
      "sit_to_stand",
      "talking",
      "salsa_dancing",
      "dwarf_idle",
      "standing_arguing",
    ];
    const animToPlay = validAnimations.includes(currentAnimation)
      ? currentAnimation
      : "bored";

    actions[animToPlay]
      ?.reset()
      .fadeIn(mixer.time > 0 ? ANIMATION_FADE_TIME : 0)
      .play();
    return () => {
      actions[animToPlay]?.fadeOut(ANIMATION_FADE_TIME);
    };
  }, [currentAnimation, actions, mixer]);

  const lerpMorphTarget = (target, value, speed = 0.1) => {
    scene.traverse((child) => {
      if (child.isSkinnedMesh && child.morphTargetDictionary) {
        const index = child.morphTargetDictionary[target];
        if (
          index === undefined ||
          child.morphTargetInfluences[index] === undefined
        ) {
          return;
        }
        child.morphTargetInfluences[index] = MathUtils.lerp(
          child.morphTargetInfluences[index],
          value,
          speed
        );
      }
    });
  };

  const [thinkingText, setThinkingText] = useState(".");

  useEffect(() => {
    if (loading) {
      const interval = setInterval(() => {
        setThinkingText((thinkingText) => {
          if (thinkingText.length === 3) {
            return ".";
          }
          return thinkingText + ".";
        });
      }, 500);
      return () => clearInterval(interval);
    }
  }, [loading]);

  return (
    <group {...props} dispose={null} ref={group}>
      {loading && (
        <Html position-y={Avatar === "fox" ? 1.6 : 1.8}>
          <div className="flex justify-center items-center -translate-x-1/2">
            <span className="relative flex h-8 w-8 items-center justify-center">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-white opacity-75"></span>
              <span className="relative inline-flex items-center justify-center duration-75 rounded-full h-8 w-8 bg-white/80">
                {thinkingText}
              </span>
            </span>
          </div>
        </Html>
      )}
      <primitive object={scene} />
    </group>
  );
}

lawyers.forEach((Avatar) => {
  useGLTF.preload(CHARACTER_FILE);
  useGLTF.preload(ANIMATIONS_FILE);
});